version: '2.1'
services:
  kafka-server:
    build:
      context: kafka-server
      dockerfile: Dockerfile
    ports:
       - "8761:8761"
    healthcheck:
      test: "exit 0"
  grpc-server:
    build:
      context: grpc-server
      dockerfile: Dockerfile
    ports:
       - "6565:6565"
    links:
     - eureka-server
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    healthcheck:
      test: "exit 0"
  endpoint:
    build:
      context: endpoint
      dockerfile: Dockerfile
    ports:
       - "8081:8081"
    links:
      - eureka-server
    depends_on:
      eureka-server:
            condition: service_healthy
      grpc-server:
            condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
